---
title: "LogisticLab"
author: "Margo Bergman"
date: "11/3/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("/Users/vaishnavishankar/Desktop/MSBA Autumn/Applied Regression"))
```

Library Packages

```{r library}
library(readxl)
library(plyr)
library(dplyr)
library(tidyverse)
library(car)
library(zoo)
```

Load Data

```{r Data}
RainAtlantaAll <- read_csv("RainAtlantaAll.csv")
```

```{r ExploreDataStructure}

dim(RainAtlantaAll)    #returns the dimensions of an object
str(RainAtlantaAll)    #returns the structure of an object
sum(is.na(RainAtlantaAll)) #returns how many observations have "na"


RainAtlantaAll$WT01 <- as.character(as.logical(RainAtlantaAll$WT01))
RainAtlantaAll$WT02 <- as.character(as.logical(RainAtlantaAll$WT02))
RainAtlantaAll$WT03 <- as.character(as.logical(RainAtlantaAll$WT03))
RainAtlantaAll$WT04 <- as.character(as.logical(RainAtlantaAll$WT04))
RainAtlantaAll$WT05 <- as.character(as.logical(RainAtlantaAll$WT05))
RainAtlantaAll$WT08 <- as.character(as.logical(RainAtlantaAll$WT08))



RainAtlantaAll$WT01 [is.na(RainAtlantaAll$WT01 )] <- '0' 
RainAtlantaAll$WT02 [is.na(RainAtlantaAll$WT02 )] <- '0' 
RainAtlantaAll$WT03 [is.na(RainAtlantaAll$WT03 )] <- '0' 
RainAtlantaAll$WT04 [is.na(RainAtlantaAll$WT04 )] <- '0'
RainAtlantaAll$WT05 [is.na(RainAtlantaAll$WT05 )] <- '0' 
RainAtlantaAll$WT08 [is.na(RainAtlantaAll$WT08 )] <- '0' 


sum(is.na(RainAtlantaAll))

RainAtlantaAll[is.na(RainAtlantaAll)] <- 0 #replaces "na" with 0. This is a choice, statistically, but you can't run the regression without it

sum(is.na(RainAtlantaAll))

View(RainAtlantaAll)

```

Select variables

```{r selectVariables}
RainLogData <- select (RainAtlantaAll,c(DATE,PRCP,TAVG, TMAX, TMIN, WSF2, WDF5,WDF2,  AWND, WT01, WT02, WT03,WT04, WT05, WT08))

```

Create Season Variable

```{r CreateSeason}

yq <- as.yearqtr(as.yearmon(RainLogData$DATE, "%Y/%m/%d") + 1/12)

RainLogData$Season <- factor(format(yq, "%q"), levels = 1:4, 
                    labels = c("winter", "spring", "summer", "fall"))


```


Create a Wind Direction factor variable


```{r WindDirection}
RainLogData$NewWindDir<-RainLogData$WDF5-23
View(RainLogData)

RainLogData$WindCat<-cut(RainLogData$NewWindDir, c(-22,22,67,112,157,202,247,292,337))

View(RainLogData)

RainLogData$NewWindCat<-revalue(RainLogData$WindCat, c("(-22,22]"="N","(22,67]"="NE","(67,112]"="E","(112,157]"="SE","(157,202]"="S","(202,247]"="SW","(247,292]"="W","(292,337]"="NW" ))

View(RainLogData)



```

Create Factor variable indicating presence of Rain

```{r Factor variable for Rain}

RainLogData$RainFac <- ifelse(RainLogData$PRCP > 0, 1, 0)
rain<-factor(RainLogData$RainFac)
View(RainLogData)

```


Create sequential logit models

```{r Logits}

rainpredict1<-glm(rain~RainLogData$AWND, data=RainLogData, family=binomial)
summary(rainpredict1)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict1), confint(rainpredict1)))

rainpredict2<-glm(rain~RainLogData$AWND + RainLogData$TAVG, data=RainLogData, family=binomial)
summary(rainpredict2)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict2), confint(rainpredict2)))

rainpredict3<-glm(rain~RainLogData$AWND + RainLogData$TAVG + RainLogData$TMAX, data=RainLogData, family=binomial)
summary(rainpredict3)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict3), confint(rainpredict3)))

rainpredict4<-glm(rain~RainLogData$AWND + RainLogData$TAVG + RainLogData$TMAX + RainLogData$TMIN, data=RainLogData, family=binomial)
summary(rainpredict4)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict4), confint(rainpredict4)))

rainpredict5<-glm(rain~RainLogData$AWND + RainLogData$TAVG + RainLogData$TMAX + RainLogData$TMIN + RainLogData$NewWindCat, data=RainLogData, family=binomial)
summary(rainpredict5)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict5), confint(rainpredict5)))

rainpredict6<-glm(rain~RainLogData$AWND + RainLogData$TAVG + RainLogData$TMAX + RainLogData$TMIN + RainLogData$NewWindCat + RainLogData$Season, data=RainLogData, family=binomial)
summary(rainpredict6)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict6), confint(rainpredict6)))


rainpredict7<-glm(rain~RainLogData$AWND + RainLogData$TMAX + RainLogData$TMIN + RainLogData$Season  + RainLogData$NewWindCat + RainLogData$WT01, data=RainLogData, family=binomial)
summary(rainpredict7)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict7), confint(rainpredict7)))


rainpredict8<-glm(rain~RainLogData$AWND + RainLogData$TMAX + RainLogData$TMIN + RainLogData$Season + RainLogData$NewWindCat + RainLogData$WT01 + RainLogData$WT03, data=RainLogData, family=binomial)
summary(rainpredict8)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict8), confint(rainpredict8)))

#Parsimonous model
rainpredict9<-glm(rain~ RainLogData$TMAX  + RainLogData$TAVG + RainLogData$TMIN + RainLogData$Season + RainLogData$NewWindCat + RainLogData$WT01 + RainLogData$WT03, data=RainLogData, family=binomial)
summary(rainpredict9)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict9), confint(rainpredict9)))

logit2prob <- function(logit){ 
  odds <- exp(logit) 
  prob <- odds / (1 + odds) 
  return(prob) 
}

prob <- logit2prob(coef(rainpredict9))
prob

#data.frame(Date = as.Date("3/16/2021"),Rain_Actual = test_df$Rain, Predicted_Rain = predicted)


rainpredict10<-glm(rain~RainLogData$AWND + RainLogData$TMAX + RainLogData$TMIN + RainLogData$Season + RainLogData$NewWindCat + RainLogData$WT01 +  RainLogData$WT03+RainLogData$WT08, data=RainLogData, family=binomial)
summary(rainpredict10)
exp(cbind(Odds_Ratio_RainVNoRain=coef(rainpredict10), confint(rainpredict10)))



```

Residual plots

```{r residuals}
rain.res<-residuals.glm(rainpredict9)
ggplot(data=RainLogData, aes(x=RainLogData$TAVG, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$TMAX, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$TMIN, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$Season, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$NewWindCat, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$WT01, y=rain.res))+geom_point()
ggplot(data=RainLogData, aes(x=RainLogData$WT03, y=rain.res))+geom_point()

```

